Repository HoshkoS/F12_2, pull requests merged in 2024-03, with the labels that each got.

#20 feat: add logger
  ASPNET-CORE-MVC/Domain/Services/LoggerInterface/ILoggerService.cs
  ASPNET-CORE-MVC/Infrastructure/Infrastructure.csproj
  ASPNET-CORE-MVC/Infrastructure/Services/Logger/LoggerService.cs
  ASPNET-CORE-MVC/ThinkTwice/Extensions/Extensions.cs
  ASPNET-CORE-MVC/ThinkTwice/Program.cs
  ASPNET-CORE-MVC/ThinkTwice/ThinkTwice.csproj
  ASPNET-CORE-MVC/ThinkTwice/ThinkTwice.sln
  ASPNET-CORE-MVC/UseCase/Services/Logger/LoggerService.cs
  ASPNET-CORE-MVC/UseCase/UseCase.csproj
Labels: documentation

#23 Implement repositories and unit of work
  ASPNET-CORE-MVC/Domain/Class1.cs
  ASPNET-CORE-MVC/Domain/Models/Category.cs
  ASPNET-CORE-MVC/Domain/Models/Transaction.cs
  ASPNET-CORE-MVC/Domain/Models/User.cs
  ASPNET-CORE-MVC/Domain/Repositories/ICategoryRepository.cs
  ASPNET-CORE-MVC/Domain/Repositories/IRepository.cs
  ASPNET-CORE-MVC/Domain/Repositories/ITransactionRepository.cs
  ASPNET-CORE-MVC/Domain/Repositories/IUnitOfWork.cs
  ASPNET-CORE-MVC/Domain/Repositories/IUserRepository.cs
  ASPNET-CORE-MVC/Infrastructure/Database/Migrations/20240314192815_001.Designer.cs
  ASPNET-CORE-MVC/Infrastructure/Database/Migrations/20240314192815_001.cs
  ASPNET-CORE-MVC/Infrastructure/Database/Migrations/ServerDbContextModelSnapshot.cs
  ASPNET-CORE-MVC/Infrastructure/Database/NewFile1.cs
  ASPNET-CORE-MVC/Infrastructure/Database/ServerDbContext.cs
  ASPNET-CORE-MVC/Infrastructure/Infrastructure.csproj
  ASPNET-CORE-MVC/Infrastructure/Repositories/CategoryRepository.cs
  ASPNET-CORE-MVC/Infrastructure/Repositories/Repository.cs
  ASPNET-CORE-MVC/Infrastructure/Repositories/TransactionRepositories.cs
  ASPNET-CORE-MVC/Infrastructure/Repositories/UnitOfWork.cs
  ASPNET-CORE-MVC/Infrastructure/Repositories/UserRepository.cs
  ASPNET-CORE-MVC/ThinkTwice/Extension/ServiceExtensions.cs
  ASPNET-CORE-MVC/ThinkTwice/Program.cs
  ASPNET-CORE-MVC/ThinkTwice/ThinkTwice.csproj
Labels: enhancement

#27 Create settings controller
  ASPNET-CORE-MVC/Infrastructure/Repositories/Repository.cs
  ASPNET-CORE-MVC/Infrastructure/stylecop.json
  ASPNET-CORE-MVC/ThinkTwice/Controllers/AuthController.cs
  ASPNET-CORE-MVC/ThinkTwice/Controllers/HomeController.cs
  ASPNET-CORE-MVC/ThinkTwice/Dtos/RegisterUserDto.cs
  ASPNET-CORE-MVC/ThinkTwice/ThinkTwice.csproj
  ASPNET-CORE-MVC/ThinkTwice/Views/Auth/Login.cshtml
  ASPNET-CORE-MVC/ThinkTwice/Views/Auth/Login.cshtml.css
  ASPNET-CORE-MVC/ThinkTwice/Views/Auth/SignUp.cshtml
  ASPNET-CORE-MVC/ThinkTwice/Views/Auth/SignUp.cshtml.css
  ASPNET-CORE-MVC/ThinkTwice/Views/Shared/_Layout.cshtml
  ASPNET-CORE-MVC/ThinkTwice/wwwroot/Assets/Images/bar_chart_growth_logo.png
Labels: enhancement

#36 Settings
  ASPNET-CORE-MVC/Domain/Dtos/CategoryDtos/CategoryDto.cs
  ASPNET-CORE-MVC/Domain/Dtos/UserDtos/UserDto.cs
  ASPNET-CORE-MVC/Domain/Models/Category.cs
  ASPNET-CORE-MVC/Domain/Models/Transaction.cs
  ASPNET-CORE-MVC/Domain/Models/User.cs
  ASPNET-CORE-MVC/Domain/Repositories/IRepository.cs
  ASPNET-CORE-MVC/Domain/Services/CategoryService/ICategoryService.cs
  ASPNET-CORE-MVC/Domain/Services/UserService/IUserService.cs
  ASPNET-CORE-MVC/Infrastructure/Repositories/Repository.cs
  ASPNET-CORE-MVC/Infrastructure/Services/CategoryService/CategoryService.cs
  ASPNET-CORE-MVC/Infrastructure/Services/UserService/UserService.cs
  ASPNET-CORE-MVC/ThinkTwice/.editorconfig
  ASPNET-CORE-MVC/ThinkTwice/Controllers/AuthController.cs
  ASPNET-CORE-MVC/ThinkTwice/Controllers/HomeController.cs
  ASPNET-CORE-MVC/ThinkTwice/Dtos/CategoryDTO.cs
  ASPNET-CORE-MVC/ThinkTwice/Dtos/RegisterUserDto.cs
  ASPNET-CORE-MVC/ThinkTwice/Extension/ServiceExtensions.cs
  ASPNET-CORE-MVC/ThinkTwice/ThinkTwice.csproj
  ASPNET-CORE-MVC/ThinkTwice/Views/Auth/Login.cshtml
  ASPNET-CORE-MVC/ThinkTwice/Views/Auth/SignUp.cshtml
  ASPNET-CORE-MVC/ThinkTwice/Views/Home/Settings.cshtml
  ASPNET-CORE-MVC/ThinkTwice/Views/Shared/_CategoryList.cshtml
  ASPNET-CORE-MVC/ThinkTwice/Views/Shared/_CategoryModal.cshtml
  ASPNET-CORE-MVC/ThinkTwice/Views/Shared/_EditCategoryModal.cshtml
  ASPNET-CORE-MVC/ThinkTwice/Views/Shared/_Layout.cshtml
  ASPNET-CORE-MVC/ThinkTwice/wwwroot/css/Settings.css
  ASPNET-CORE-MVC/ThinkTwice/wwwroot/css/_CategoryModal.css
  ASPNET-CORE-MVC/ThinkTwice/wwwroot/js/_CategoryModal.js
Labels: enhancement

#37 Implement async methods
  ASPNET-CORE-MVC/Domain/Dtos/CategoryDtos/CategoryDto.cs
  ASPNET-CORE-MVC/Domain/Dtos/UserDtos/UserDto.cs
  ASPNET-CORE-MVC/Domain/Models/Transaction.cs
  ASPNET-CORE-MVC/Domain/Models/User.cs
  ASPNET-CORE-MVC/Domain/Repositories/IRepository.cs
  ASPNET-CORE-MVC/Domain/Repositories/IUnitOfWork.cs
  ASPNET-CORE-MVC/Domain/Services/CategoryService/ICategoryService.cs
  ASPNET-CORE-MVC/Domain/Services/LoggerInterface/ILoggerService.cs
  ASPNET-CORE-MVC/Domain/Services/UserService/IUserService.cs
  ASPNET-CORE-MVC/Infrastructure/Repositories/Repository.cs
  ASPNET-CORE-MVC/Infrastructure/Repositories/UnitOfWork.cs
  ASPNET-CORE-MVC/Infrastructure/Services/CategoryService/CategoryService.cs
  ASPNET-CORE-MVC/Infrastructure/Services/UserService/UserService.cs
  ASPNET-CORE-MVC/ThinkTwice/Controllers/AuthController.cs
  ASPNET-CORE-MVC/ThinkTwice/Controllers/HomeController.cs
  ASPNET-CORE-MVC/ThinkTwice/Dtos/CategoryDTO.cs
  ASPNET-CORE-MVC/ThinkTwice/Dtos/RegisterUserDto.cs
  ASPNET-CORE-MVC/ThinkTwice/Extension/ServiceExtensions.cs
  ASPNET-CORE-MVC/ThinkTwice/Models/ErrorViewModel.cs
Labels: enhancement

#41 Implement xunit test with Nsubstitute
  ASPNET-CORE-MVC/Tests/GlobalUsings.cs
  ASPNET-CORE-MVC/Tests/HomeControllerTests.cs
  ASPNET-CORE-MVC/Tests/Tests.csproj
  ASPNET-CORE-MVC/ThinkTwice/ThinkTwice.sln
Labels: enhancement

#44 Add http context storage
  ASPNET-CORE-MVC/Infrastructure/Infrastructure.csproj
  ASPNET-CORE-MVC/Infrastructure/Services/UserService/UserService.cs
  ASPNET-CORE-MVC/ThinkTwice/Controllers/HomeController.cs
  ASPNET-CORE-MVC/ThinkTwice/Program.cs
Labels: enhancement

#46 hot fix
  ASPNET-CORE-MVC/ThinkTwice/Controllers/HomeController.cs
Labels: bug
